In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
%cd ..

/Users/kristophermiltiadou/Documents/UniWork/Cambridge/Thesis/CODE/iREC


In [4]:
import torch
import torch.distributions as dist
import math
import matplotlib.pyplot as plt
import pickle as pkl

from tqdm.notebook import tqdm
from rec.beamsearch.distributions.CodingSampler import CodingSampler
from rec.beamsearch.distributions.EmpiricalMixturePosterior import EmpiricalMixturePosterior
from rec.beamsearch.samplers.GreedySampling import GreedySampler
from rec.beamsearch.Coders.Encoder import Encoder as Empirical_Encoder
from models.BayesianLinRegressor import BayesLinRegressor
from rec.utils import kl_estimate_with_mc, plot_samples_in_2d, plot_running_sum_2d, plot_pairs_of_samples
from rec.OptimisingVars.FinalJointOptimiser import FinalJointOptimiser

In [5]:
def encode_sample(target, omega=8, epsilon=0.,
                  n_empirical_samples=10, seed=0, beamwidth=1, optimising_vars=False, aux_vars=None):
    
    encoder = Empirical_Encoder(target,
                                seed,
                                CodingSampler,
                                GreedySampler,
                                EmpiricalMixturePosterior,
                                omega,
                                n_empirical_samples,
                                epsilon=epsilon,
                                beamwidth=beamwidth
                                )
    
    return encoder, *encoder.run_encoder()

In [6]:
def create_blr_problem(dim, seed):
    
    initial_seed_target = seed
    blr = BayesLinRegressor(prior_mean=torch.zeros(dim),
                        prior_alpha=1,
                        signal_std=1,
                        num_targets=10000,
                        seed=initial_seed_target)
    blr.sample_feature_inputs()
    blr.sample_regression_targets()
    blr.posterior_update()
    target = blr.weight_posterior
    return blr, target

In [10]:
dim = 10
beamwidth = 20
omega = 5
blr_seed = 1
b, t = create_blr_problem(dim=dim, seed=blr_seed)
num_compressed_samples = 50

torch.manual_seed(0)
seeds = torch.randint(low = 0, high = int(1e6), size=(num_compressed_samples,))
epsilons = [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3]

for eps in epsilons:
    exp_dict = {}
    exp_dict['seeds'] = seeds.numpy()
    exp_dict['target_mean'] = t.mean.numpy()8
    exp_dict['target_covar'] = t.covariance_matrix.numpy()
    exp_dict['compressed_samples'] = []
    exp_dict['compressed_samples_idxs'] = []
    pbar = tqdm(enumerate(seeds), total=num_compressed_samples)
    for i, s in pbar:
        enc, z, idx = encode_sample(target=t, beamwidth=beamwidth, epsilon=eps, omega=omega, seed=s, n_empirical_samples=50)
        idxs_to_transmit = idx[0]
        best_sample = z[0]
        exp_dict['compressed_samples'].append(best_sample.numpy())
        exp_dict['compressed_samples_idxs'].append(idxs_to_transmit.numpy())
        pbar.set_description(f"Coded sample {i + 1}, has log prob of {t.log_prob(best_sample)}")

    with open(f"PickledStuff/Dim{dim}/Empirical_Epsilon{eps}_Beam{beamwidth}_Omega{omega}.pkl", "wb") as f:
        pkl.dump(exp_dict, f)

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

In [290]:
big_z = 0
for sample in exp_dict['compressed_samples']:
    big_z += sample

In [291]:
meany = big_z / num_compressed_samples

In [292]:
t.log_prob(torch.tensor(meany))

tensor(6.6819)

In [293]:
t.log_prob(t.mean)

tensor(6.6854)

In [277]:
test = pkl.load(open("PickledStuff/Dim2/Empirical_Epsilon0.2.pkl", "rb"))

In [297]:
exp_dict['compressed_samples_idxs']

[array([595., 300.], dtype=float32),
 array([227., 640.], dtype=float32),
 array([233., 375.], dtype=float32),
 array([160., 609.], dtype=float32),
 array([268., 171.], dtype=float32),
 array([212., 535.], dtype=float32),
 array([563., 463.], dtype=float32),
 array([637., 570.], dtype=float32),
 array([571., 386.], dtype=float32),
 array([ 62., 504.], dtype=float32),
 array([146., 459.], dtype=float32),
 array([614.,  88.], dtype=float32),
 array([631., 123.], dtype=float32),
 array([117., 431.], dtype=float32),
 array([176., 549.], dtype=float32),
 array([344., 299.], dtype=float32),
 array([460., 292.], dtype=float32),
 array([458., 471.], dtype=float32),
 array([393., 114.], dtype=float32),
 array([ 36., 433.], dtype=float32),
 array([ 17., 125.], dtype=float32),
 array([ 24., 505.], dtype=float32),
 array([548., 154.], dtype=float32),
 array([649., 592.], dtype=float32),
 array([310.,  70.], dtype=float32),
 array([276.,  49.], dtype=float32),
 array([496., 339.], dtype=float32),
 

In [279]:
test = pkl.load(open("PickledStuff/Dim2/Empirical_Epsilon0.3.pkl", "rb"))

In [280]:
t.log_prob(torch.tensor(test['compressed_samples'][-1]))

tensor(6.6562)